version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.4.0-stretch-browsers

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: phantomjs
      
      - run:
          name: Install tools
          command: |
            if ! [ $(which phantomjs) ]; then                
              sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
              sudo chmod ugo+x /usr/local/bin/phantomjs
            fi
            if ! [ $(which stylus) ]; then
              sudo npm install stylus -g            
            fi
            
            sudo apt-get update
            sudo apt-get install -y pngcrush

      - save_cache:
          key: phantomjs
          paths:            
            - /usr/local/bin
            - /usr/local/lib/node_modules

      - checkout

      - run:        
          name: Build
          command: |
            make all release
